Repository laminas/laminas-feed, pull requests merged in 2022-07, with the labels that each got.

#53 Fixes Markdown linting issues
  README.md
  composer.json
  composer.lock
  docs/book/find-feeds.md
  docs/book/importing.md
  docs/book/intro.md
  docs/book/psr7-clients.md
Labels: Documentation, Enhancement

#52 Mention creation of Feeds in composer.json
  composer.json
Labels: Documentation, Enhancement

#56 Reformat admonitions
  docs/book/find-feeds.md
  docs/book/importing.md
  docs/book/intro.md
Labels: Documentation

#59 Adjusted built-in plugin managers for `psr/container:^2` compatibility
  psalm-baseline.xml
  src/Reader/ExtensionManager.php
  src/Reader/ExtensionManagerInterface.php
  src/Reader/ExtensionPluginManager.php
  src/Reader/StandaloneExtensionManager.php
  src/Writer/ExtensionManagerInterface.php
  test/Reader/TestAsset/CustomExtensionManager.php
Labels: BC Break, Bug

#58 Apply PHP 7.4 syntax and typed property
  src/Reader/Http/LaminasHttpClientDecorator.php
  src/Reader/Http/Psr7ResponseDecorator.php
  src/Reader/Http/Response.php
  src/Reader/StandaloneExtensionManager.php
  src/Writer/StandaloneExtensionManager.php
  test/PubSubHubbub/Subscriber/CallbackTest.php
  test/Reader/Entry/AtomStandaloneEntryTest.php
  test/Reader/Entry/AtomTest.php
  test/Reader/Entry/CommonTest.php
  test/Reader/Entry/RssTest.php
  test/Reader/Feed/AtomSourceTest.php
  test/Reader/Feed/AtomTest.php
  test/Reader/Feed/CommonTest.php
  test/Reader/Feed/RssTest.php
  test/Reader/Integration/GooglePlayPodcastRss2Test.php
  test/Reader/Integration/HOnlineComAtom10Test.php
  test/Reader/Integration/LautDeRdfTest.php
  test/Reader/Integration/PodcastIndexRss2Test.php
  test/Reader/Integration/PodcastRss2Test.php
  test/Reader/Integration/WordpressAtom10Test.php
  test/Reader/Integration/WordpressRss2DcAtomTest.php
  test/Reader/ReaderTest.php
  test/Reader/StandaloneExtensionManagerTest.php
  test/Reader/TestAsset/CustomExtensionManager.php
  test/Writer/DeletedTest.php
  test/Writer/EntryTest.php
  test/Writer/Extension/ITunes/EntryTest.php
  test/Writer/Extension/ITunes/FeedTest.php
  test/Writer/FeedTest.php
  test/Writer/Renderer/Entry/AtomTest.php
  test/Writer/Renderer/Entry/RssTest.php
  test/Writer/Renderer/Feed/AtomTest.php
  test/Writer/Renderer/Feed/RssTest.php
  test/Writer/StandaloneExtensionManagerTest.php
  test/Writer/TestAsset/CustomExtensionManager.php
Labels: Enhancement
